#!/usr/bin/env php
<?php

define( 'PATH_ROOT', dirname( __DIR__ ) . '/app' );
define( 'PATH_SRC', PATH_ROOT . '/src' );
define( 'PATH_RSC', PATH_ROOT . '/resources' );

define( 'PATH_CACHE', PATH_RSC . '/cache' );
define( 'PATH_LOCALES', PATH_RSC . '/locales' );

define( 'PATH_PUBLIC', PATH_ROOT . '/web' );
define( 'PATH_VENDOR', PATH_ROOT  );

require_once __DIR__.'/vendor/autoload.php';

$app = new Silex\Application();

require __DIR__.'/resources/config/dev.php';
require __DIR__.'/src/app.php';

$console = require __DIR__.'/src/console.php';
$console->run();
