#!/usr/bin/env php
<?php

define( 'PATH_ROOT', dirname( __DIR__ ).'/src' );
define( 'PATH_SRC', PATH_ROOT . '/resources' );

define( 'PATH_CACHE', PATH_SRC . '/cache' );
define( 'PATH_LOCALES', PATH_SRC . '/locales' );

define( 'PATH_PUBLIC', PATH_ROOT . '/web' );
define( 'PATH_VENDOR', PATH_ROOT  );

require_once __DIR__.'/vendor/autoload.php';

$app = new Silex\Application();

require __DIR__.'/resources/config/dev.php';
require __DIR__.'/resources/app.php';

$console = require __DIR__.'/resources/console.php';
$console->run();
