#!/usr/bin/env php
<?php

define( 'PATH_ROOT', dirname( __DIR__ ). '/src' );
define( 'PATH_SRC', PATH_ROOT . '/src' );

require_once __DIR__.'/vendor/autoload.php';

$app = new Silex\Application();

require __DIR__.'/resources/config/dev.php';
require __DIR__.'/src/app.php';

$console = require __DIR__.'/src/console.php';
$console->run();
